spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cafe?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver