server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://team04-db.c3ki4qoo6im1.ap-northeast-2.rds.amazonaws.com:3306/BeanSpot
    username: admin
    password: "rds5%6^7&"
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 6379
      password: ${custom.prod.redis.password}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show-sql: false
        format_sql: false
        use_sql_comments: false
        highlight-sql: false
logging:
  level:
    org.hibernate.SQL: INFO
    org.hibernate.orm.jdbc.bind: INFO
    org.hibernate.orm.jdbc.extract: INFO
    org.springframework.transaction.interceptor: INFO