server:
  port: 8080
  forward-headers-strategy: native
spring:
  application:
    name: WEB3_4_Poten_BE
  profiles:
    active: dev
    include: secret
  data:
    redis:
      host: localhost
      port: 6379
      password: # Redis password if applicable
      database: 0 # Redis database index
      timeout: 60000 # Connection timeout in milliseconds
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms # Negative for no limit
  # Optional: Spring Session configuration if you plan to use Redis for session management
  datasource:
    url: jdbc:h2:./db_dev;MODE=MySQL
    username: sa
    password:
    driver-class-name: org.h2.Driver
    hikari:
      auto-commit: false
  session:
    store-type: redis
    redis:
      namespace: beanspot:session # Prefix for session keys
      flush-mode: on-save
  web:
    resources:
      add-mappings: false
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 50MB
  output:
    ansi:
      enabled: always
    hikari:
      auto-commit: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        default_batch_fetch_size: 100
        show-sql: true
        format_sql: true
        use_sql_comments: true
        highlight-sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-Id: ON_SECRET
            client-secret: ON_SECRET
            scope:
              - email
              - profile
            client-name: Google
            authorization-grant-type: authorization_code
            redirect-uri: '{baseUrl}/{action}/oauth2/code/{registrationId}'
          kakao:
            client-Id: ON_SECRET
            scope:
              - profile_nickname
              - profile_image
              - account_email
            client-name: Kakao
            authorization-grant-type: authorization_code
            redirect-uri: '{baseUrl}/{action}/oauth2/code/{registrationId}'
          naver:
            client-id: ON_SECRET
            scope:
              - name
              - email
              - profile_image
            client-name: Naver
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: '{baseUrl}/{action}/oauth2/code/{registrationId}'
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-info-authentication-method: header
            user-name-attribute: response

springdoc:
  default-produces-media-type: application/json;charset=UTF-8
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.orm.jdbc.extract: TRACE
    org.springframework.transaction.interceptor: TRACE
custom:
  jwt:
    secretKey: abcdefghijklmnopqrstuvwxyz0123456789abcdefghijklmnopqrstuvwxyz0123456789abcdefghijklmnopqrstuvwxyz0123456789
  dev:
    cookieDomain: localhost
    frontUrl: "http://${custom.dev.cookieDomain}:3000"
    backUrl: "http://${custom.dev.cookieDomain}:${server.port}"
  prod:
    cookieDomain: beanspot.shop
    frontUrl: "https://www.${custom.prod.cookieDomain}"
    backUrl: "https://api.${custom.prod.cookieDomain}"
  site:
    cookieDomain: "${custom.dev.cookieDomain}"
    frontUrl: "${custom.dev.frontUrl}"
    backUrl: "${custom.dev.backUrl}"
    name:
  accessToken:
    expirationSeconds: "#{60 * 20}"
  genFile:
    dirPath:

  admin:
    email: admin@beanspot.com
    password: adminPassword