
spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            clientId: 6d7b673f68e36faa4f581fbc771b861d
          naver:
            client-id: tGaeBPDTwqI9SxWr_VR1
custom:
  jwt:
    secretKey: abcdefghijklmnopqrstuvwxyz0123456789abcdefghijklmnopqrstuvwxyz0123456789abcdefghijklmnopqrstuvwxyz0123456789